### ISSUE TITLE
Nullpointerexception

### ISSUE THREAD

**Issue by rdutta** [Tony905x/pet-to-npc-transmog#4]
```
Caused by: java.lang.NullPointerException: null
        at com.pettonpc.NpcFollowerPanel.updateFieldsWithNpcData(NpcFollowerPanel.java:482)
        at com.pettonpc.NpcFollowerPlugin.panelChange(NpcFollowerPlugin.java:213)
        at com.pettonpc.NpcFollowerPanel.lambda$new$0(NpcFollowerPanel.java:223)
        at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1264)
        at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:589)
        at com.pettonpc.NpcFollowerPanel.loadLastConfiguration(NpcFollowerPanel.java:353)
        at com.pettonpc.NpcFollowerPlugin.startUp(NpcFollowerPlugin.java:97)
        at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:438)
```

This is thrown when installing from the plugin hub and also when starting the client (1.10.42-SNAPSHOT)

**Comment by Tony905x** [comment]
Thanks, yes this is likely related to the bug that was brought up because the program didn't have a way to handle when there wasn't any previously saved data.  I made the fix and will likely submit it to the runelite team for review tonight or tomorrow
